services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: hh-app
    restart: unless-stopped
    working_dir: /var/www/backend
    volumes:
      - ../backend:/var/www/backend
      - ../frontend:/var/www/frontend
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
      - redis
    networks:
      - hh

  nginx:
    image: nginx:1.27-alpine
    container_name: hh-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../backend/public:/var/www/backend/public
      - ../frontend/dist:/var/www/frontend/dist
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - hh

  postgres:
    image: postgres:16-alpine
    container_name: hh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - hh_postgres_data:/var/lib/postgresql/data
    networks:
      - hh

  redis:
    image: redis:7-alpine
    container_name: hh-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - hh_redis_data:/data
    networks:
      - hh
    command: ["redis-server", "--appendonly", "yes"]

networks:
  hh:
    driver: bridge

volumes:
  hh_postgres_data:
  hh_redis_data:
