services:
  app:
    build:
      context: ../  # Контекст теперь корень проекта
      dockerfile: docker/Dockerfile  # путь к Dockerfile
    container_name: hh-app
    user: "1000:1000"
    restart: unless-stopped
    working_dir: /var/www/backend  # рабочая директория - backend
    volumes:
      - ../backend:/var/www/backend  # монтируем backend
      - ../frontend:/var/www/frontend  # монтируем frontend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - hh

  nginx:
    image: nginx:1.27-alpine
    container_name: hh-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../backend/public:/var/www/backend/public  # Laravel public
      - ../frontend/dist:/var/www/frontend/dist  # для собранного Vue (потом)
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # конфиг nginx
    depends_on:
      - app
    networks:
      - hh

  postgres:
    image: postgres:16-alpine
    container_name: hh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - hh_postgres_data:/var/lib/postgresql/data
    networks:
      - hh

networks:
  hh:
    driver: bridge

volumes:
  hh_postgres_data:
